### PR TITLE
Use cqlsh to backup schema instead of depreciated cassandra-cli

### PR DESCRIPTION
**Pull request by matkam**
Cassandra CLI doesn't dump newer tables. Switching to ```cqlsh``` instead

### CODE REVIEW

**Comment by tbarbugli** [comment]
could you elaborate on this?

**Comment by matkam** [comment]
So trying to run ```show schema``` with ```cassandra-cli``` on Cassandra 2.1, I get the following error and most of my tables aren't shown:
```
$ echo -e "show schema;\n" | cassandra-cli
Connected to: "prod" on 127.0.0.1/9160
Welcome to Cassandra CLI version 2.1.8

The CLI is deprecated and will be removed in Cassandra 2.2.  Consider migrating to cqlsh.
CQL is fully backwards compatible with Thrift data; see http://www.datastax.com/dev/blog/thrift-to-cql3

Type 'help;' or '?' for help.
Type 'quit;' or 'exit;' to quit.

[default@unknown] show schema;

WARNING: CQL3 tables are intentionally omitted from 'show schema' output.
See https://issues.apache.org/jira/browse/CASSANDRA-4377 for details.
```

Using ```describe schema``` with ```cqlsh``` all my tables are dumped just fine. Seems like they are deprecating ```cassandra-cli``` in favor of ```cqlsh```

**Comment by tbarbugli** [comment]
good point, thank you for your contribution. Please add yourself to the contributor manifest as well :)

**Comment by matkam** [comment]
Great, will do. Thanks for the merge!

**Pull request merged**
