### PR TITLE
Update README.md

### PR DESCRIPTION
**Pull request by zachaller**
Will not run on all nodes unless you set --connection-pool-size update doc to help someone else that runs into the issues i had.

### CODE REVIEW

**Comment by tbarbugli** [comment]
thank you for the PR, could you elaborate on the issue? this sounds more like a bug than a documentation issue

**Comment by zachaller** [comment]
So what was happening is when trying to perform a backup on 13 nodes one of the nodes would always fail to start the upload process to s3, after digging around a bit and looking are the code for the number 12 i noticed it there once i increased the number everything worked fine and all nodes would push to s3

**Comment by tbarbugli** [comment]
I can't reproduce this, it would be great if you could re-run the command and paste the output here together with some system information (eg. python version, OS...) :)

**Comment by zachaller** [comment]
So the thing is it dose not seem to leave much for a log here is what i have though

```
/usr/local/bin/cassandra-snapshotter --aws-access-key-id=xxxxxxxxxxxxxxxxxxxx --aws-secret-access-key=xxxxxxxxxxxxxxxxxxxx --s3-bucket-name=cassa-bucket --s3-bucket-region=us-east-1 --s3-base-path=ec2_east_daily backup --hosts=cassa-e1d-00,cassa-e1d-01,cassa-e1d-02,cassa-e1d-03,cassa-e1d-04,cassa-e1d-05,cassa-e1d-06,cassa-e1d-07,cassa-e1d-08,cassa-e1d-09,cassa-e1d-10,cassa-e1d-11,cassa-e1d-12 --user=cassabackup --new-snapshot --cassandra-data-path=/ephemeral/cassandra/data --connection-pool-size 4
[cassa-e1d-00] Executing task 'node_start_backup'
[cassa-e1d-01] Executing task 'node_start_backup'
[cassa-e1d-02] Executing task 'node_start_backup'
[cassa-e1d-03] Executing task 'node_start_backup'
[cassa-e1d-04] Executing task 'node_start_backup'
[cassa-e1d-05] Executing task 'node_start_backup'
[cassa-e1d-06] Executing task 'node_start_backup'
[cassa-e1d-07] Executing task 'node_start_backup'
[cassa-e1d-08] Executing task 'node_start_backup'
[cassa-e1d-09] Executing task 'node_start_backup'
[cassa-e1d-10] Executing task 'node_start_backup'
[cassa-e1d-11] Executing task 'node_start_backup'
[cassa-e1d-12] Executing task 'node_start_backup'
[cassa-e1d-00] Executing task 'upload_node_backups'
[cassa-e1d-01] Executing task 'upload_node_backups'
[cassa-e1d-02] Executing task 'upload_node_backups'
[cassa-e1d-03] Executing task 'upload_node_backups'
[cassa-e1d-04] Executing task 'upload_node_backups'
[cassa-e1d-05] Executing task 'upload_node_backups'
[cassa-e1d-06] Executing task 'upload_node_backups'
[cassa-e1d-07] Executing task 'upload_node_backups'
[cassa-e1d-08] Executing task 'upload_node_backups'
[cassa-e1d-09] Executing task 'upload_node_backups'
[cassa-e1d-10] Executing task 'upload_node_backups'
[cassa-e1d-11] Executing task 'upload_node_backups'
[cassa-e1d-12] Executing task 'upload_node_backups'
[cassa-e1d-09] sudo: cassandra-snapshotter-agent  create-upload-manifest --manifest_path=/tmp/backupmanifest --snapshot_name=20150713191429 --snapshot_keyspaces= --snapshot_table= --data_path=/ephemeral/cassandra/data
[cassa-e1d-11] sudo: cassandra-snapshotter-agent  create-upload-manifest --manifest_path=/tmp/backupmanifest --snapshot_name=20150713191429 --snapshot_keyspaces= --snapshot_table= --data_path=/ephemeral/cassandra/data
[cassa-e1d-12] sudo: cassandra-snapshotter-agent  create-upload-manifest --manifest_path=/tmp/backupmanifest --snapshot_name=20150713191429 --snapshot_keyspaces= --snapshot_table= --data_path=/ephemeral/cassandra/data
[cassa-e1d-10] sudo: cassandra-snapshotter-agent  create-upload-manifest --manifest_path=/tmp/backupmanifest --snapshot_name=20150713191429 --snapshot_keyspaces= --snapshot_table= --data_path=/ephemeral/cassandra/data
[cassa-e1d-09] sudo: cassandra-snapshotter-agent  put --aws-access-key-id=xxxxxxxxxxxxxxxxxxxx --aws-secret-access-key=xxxxxxxxxxxxxxxxxxxx --s3-bucket-name=gf-backup-cassandra --s3-bucket-region=us-east-1  --s3-base-path=ec2_east_daily/20150713191429/cassa-e1d-09 --manifest=/tmp/backupmanifest --concurrency=4
[cassa-e1d-09] out: lzop 1.03
[cassa-e1d-09] out: LZO library 2.06
[cassa-e1d-09] out: Copyright (C) 1996-2010 Markus Franz Xaver Johannes Oberhumer
[cassa-e1d-11] sudo: cassandra-snapshotter-agent  put --aws-access-key-id=xxxxxxxxxxxxxxxxxxxx --aws-secret-access-key=xxxxxxxxxxxxxxxxxxxx --s3-bucket-name=gf-backup-cassandra --s3-bucket-region=us-east-1  --s3-base-path=ec2_east_daily/20150713191429/cassa-e1d-11 --manifest=/tmp/backupmanifest --concurrency=4
[cassa-e1d-12] sudo: cassandra-snapshotter-agent  put --aws-access-key-id=xxxxxxxxxxxxxxxxxxxx --aws-secret-access-key=xxxxxxxxxxxxxxxxxxxx --s3-bucket-name=gf-backup-cassandra --s3-bucket-region=us-east-1  --s3-base-path=ec2_east_daily/20150713191429/cassa-e1d-12 --manifest=/tmp/backupmanifest --concurrency=4
[cassa-e1d-10] sudo: cassandra-snapshotter-agent  put --aws-access-key-id=xxxxxxxxxxxxxxxxxxxx --aws-secret-access-key=xxxxxxxxxxxxxxxxxxxx --s3-bucket-name=gf-backup-cassandra --s3-bucket-region=us-east-1  --s3-base-path=ec2_east_daily/20150713191429/cassa-e1d-10 --manifest=/tmp/backupmanifest --concurrency=4
[cassa-e1d-11] out: lzop 1.03
[cassa-e1d-11] out: LZO library 2.06
[cassa-e1d-11] out: Copyright (C) 1996-2010 Markus Franz Xaver Johannes Oberhumer
[cassa-e1d-12] out: lzop 1.03
[cassa-e1d-12] out: LZO library 2.06
[cassa-e1d-12] out: Copyright (C) 1996-2010 Markus Franz Xaver Johannes Oberhumer
[cassa-e1d-10] out: lzop 1.03
[cassa-e1d-10] out: LZO library 2.06
[cassa-e1d-10] out: Copyright (C) 1996-2010 Markus Franz Xaver Johannes Oberhumer
```


as you can see i set it to 4 and so I only get the 4 create-upload-manifest commands executed and then in the s3 bucket there is only 4 node i have let it run a whole backup and it never runs on all the nodes

**Comment by tbarbugli** [comment]
This should be a reported as a bug rather than a doc improvement. I can't reproduce this though

**Pull request closed without merging**
